/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSocialMediaRouteImport } from './routes/services.social-media'
import { Route as ServicesSeoRouteImport } from './routes/services.seo'
import { Route as ServicesPpcRouteImport } from './routes/services.ppc'
import { Route as ServicesContentMarketingRouteImport } from './routes/services.content-marketing'
import { Route as ServicesBlockchainRouteImport } from './routes/services.blockchain'
import { Route as ServicesAppDevelopmentRouteImport } from './routes/services.app-development'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSocialMediaRoute = ServicesSocialMediaRouteImport.update({
  id: '/social-media',
  path: '/social-media',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSeoRoute = ServicesSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesPpcRoute = ServicesPpcRouteImport.update({
  id: '/ppc',
  path: '/ppc',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesContentMarketingRoute =
  ServicesContentMarketingRouteImport.update({
    id: '/content-marketing',
    path: '/content-marketing',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesBlockchainRoute = ServicesBlockchainRouteImport.update({
  id: '/blockchain',
  path: '/blockchain',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAppDevelopmentRoute = ServicesAppDevelopmentRouteImport.update({
  id: '/app-development',
  path: '/app-development',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/services/app-development': typeof ServicesAppDevelopmentRoute
  '/services/blockchain': typeof ServicesBlockchainRoute
  '/services/content-marketing': typeof ServicesContentMarketingRoute
  '/services/ppc': typeof ServicesPpcRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/social-media': typeof ServicesSocialMediaRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/services/app-development': typeof ServicesAppDevelopmentRoute
  '/services/blockchain': typeof ServicesBlockchainRoute
  '/services/content-marketing': typeof ServicesContentMarketingRoute
  '/services/ppc': typeof ServicesPpcRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/social-media': typeof ServicesSocialMediaRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/services/app-development': typeof ServicesAppDevelopmentRoute
  '/services/blockchain': typeof ServicesBlockchainRoute
  '/services/content-marketing': typeof ServicesContentMarketingRoute
  '/services/ppc': typeof ServicesPpcRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/social-media': typeof ServicesSocialMediaRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/services/app-development'
    | '/services/blockchain'
    | '/services/content-marketing'
    | '/services/ppc'
    | '/services/seo'
    | '/services/social-media'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/services/app-development'
    | '/services/blockchain'
    | '/services/content-marketing'
    | '/services/ppc'
    | '/services/seo'
    | '/services/social-media'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/services/app-development'
    | '/services/blockchain'
    | '/services/content-marketing'
    | '/services/ppc'
    | '/services/seo'
    | '/services/social-media'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/social-media': {
      id: '/services/social-media'
      path: '/social-media'
      fullPath: '/services/social-media'
      preLoaderRoute: typeof ServicesSocialMediaRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/seo': {
      id: '/services/seo'
      path: '/seo'
      fullPath: '/services/seo'
      preLoaderRoute: typeof ServicesSeoRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ppc': {
      id: '/services/ppc'
      path: '/ppc'
      fullPath: '/services/ppc'
      preLoaderRoute: typeof ServicesPpcRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/content-marketing': {
      id: '/services/content-marketing'
      path: '/content-marketing'
      fullPath: '/services/content-marketing'
      preLoaderRoute: typeof ServicesContentMarketingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/blockchain': {
      id: '/services/blockchain'
      path: '/blockchain'
      fullPath: '/services/blockchain'
      preLoaderRoute: typeof ServicesBlockchainRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/app-development': {
      id: '/services/app-development'
      path: '/app-development'
      fullPath: '/services/app-development'
      preLoaderRoute: typeof ServicesAppDevelopmentRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesAppDevelopmentRoute: typeof ServicesAppDevelopmentRoute
  ServicesBlockchainRoute: typeof ServicesBlockchainRoute
  ServicesContentMarketingRoute: typeof ServicesContentMarketingRoute
  ServicesPpcRoute: typeof ServicesPpcRoute
  ServicesSeoRoute: typeof ServicesSeoRoute
  ServicesSocialMediaRoute: typeof ServicesSocialMediaRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesAppDevelopmentRoute: ServicesAppDevelopmentRoute,
  ServicesBlockchainRoute: ServicesBlockchainRoute,
  ServicesContentMarketingRoute: ServicesContentMarketingRoute,
  ServicesPpcRoute: ServicesPpcRoute,
  ServicesSeoRoute: ServicesSeoRoute,
  ServicesSocialMediaRoute: ServicesSocialMediaRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRouteWithChildren,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
